---
title: "Travel Journey"
author: "Small Ni and Big Fu"
date: "Updated On: 2022-08-03"
output: 
        html_document:
                keep_md: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(leaflet)
library(tidyverse)
library(lubridate)
library(RCurl)
library(htmltools)
library(mapview)
library(prettydoc)
library(leafpop)
```

```{r read and process data, include=FALSE}
# read data from input folder
df_raw <- read_csv("./Input/travel_places.csv")
#df_raw <- read_csv("https://raw.githubusercontent.com/nealxun/TravelPlaces/master/travel_places.csv")

df_places <- df_raw %>%
        mutate(date = as.Date(date, format = "%m/%d/%y"),
               #month = floor_date(date, unit = "months"),
               quarter = paste0(as.character(year(date)), "Q", as.character(quarter(date)))
               #year = floor_date(date, unit = "years")
        ) %>% 
        mutate(info = paste(sep = "<br/>", num, date, place))

# put number on every nth visit
n <- 10
ls_num <- c(1, seq(from = 10, to = nrow(df_places), by = n), nrow(df_places)) %>% 
        unique()
df_places_selected <- df_places %>%
        filter(num %in% ls_num)

```

### Where did we travel?

```{r travel map, echo = FALSE, warning=FALSE, message=FALSE}
# place information (visit sequence, date, and name), show when hover the mice
nums <- paste0("<b>", df_places$num, "</b>")
placesInfo <- paste(sep = "<br/>", nums, df_places$date, df_places$place)

# pictures link
placesPics <- df_raw$pic

# customized icons
icon_list <- iconList(
        nature = makeIcon("./Icons/national-park-map-icons.png", 
                          iconWidth = 24, iconHeight = 30),
        city = makeIcon("./Icons/city_icon.png", 
                        iconWidth = 24, iconHeight = 30)
        )


# draw the map
df_places %>% 
        leaflet() %>%
        addTiles() %>%
        addMarkers(clusterOptions = markerClusterOptions(),
                 lat = ~latitude, lng = ~longtitude,
                 label = lapply(placesInfo, HTML), # use HTML to display multiple lines
                 popup = popupImage(placesPics),
                 #color = ~color
                 icon = ~icon_list[df_places$icon]
                 ) %>% 
        # add numbers on each location
        addLabelOnlyMarkers(lat = ~latitude, lng = ~longtitude, label = ~as.character(num),
                            labelOptions = labelOptions(noHide = TRUE, textOnly = FALSE,
                                                        textsize = "8px", opacity = 0.8),
                            data = df_places_selected)
        # add legend, could potentially add to be visited places
        #addLegend(labels = unique(df_places$icon), col = unique(df_places$color))

```


### When did we travel?

```{r travel date, echo = FALSE, warning=FALSE, message=FALSE}
df <- df_places %>% 
        group_by(quarter) %>% 
        summarise(visit_num = n())
df_label <- df_places %>% 
        group_by(quarter) %>% 
        summarise(visit_num = n()) %>% 
        ungroup() %>% 
        add_row(quarter = c("2020Q1", "2020Q2", "2020Q3"), 
                visit_num = c(0, 0, 0))

ggplot(df, aes(x = quarter, y = visit_num, label = visit_num)) +
        geom_bar(fill = "#669933", alpha = 0.6, stat = "identity") +
        # add label
        geom_text(aes(x = quarter, y = visit_num, label = visit_num), size = 4, 
                  position = position_stack(vjust = 1.05), data = df_label) + 
        annotate(geom = "text", x = "2020Q1", y = 0.5, label = "Stay at Home Order", 
                 hjust = "left", size = 3, color = "darksalmon") +
        # remove x axis label overlap
        #scale_x_discrete(guide = guide_axis(check.overlap = TRUE)) +
        scale_x_discrete(guide = guide_axis(n.dodge = 2)) +
        labs(x = "", y = "", title = "Number of Visits Over Time") +
        theme_minimal() +
        # remove all the grid
        theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
              axis.text.y = element_blank(), axis.ticks.y = element_blank())


```

